source "https://rubygems.org"
ruby "2.0.0"
gem "rubygems-update", "~> 2.2.2"
gem "sinatra", "~> 1.4.4"
gem "nokogiri", "~> 1.6.1"
gem "builder", "~> 3.2.2"
gem "rack", "~> 1.5.2"
gem "tilt", "~> 1.4.1"
gem "rack-protection", "~> 1.5.2"
gem "mini_portile", "~> 0.5.2"
gem "bundler", "~> 1.5.2"
gem "libxml-ruby", "~> 2.7.0"
gem "gocardless", "~> 1.8.0"
gem "newrelic_rpm", "~> 3.7.2.192"
gem "mandrill-api", "~> 1.0.51"
gem 'httparty', :git => 'git://github.com/kathedley/httparty'